PKNU-JavaStudy/mozip_backend

src/main/java/com/mozip/domain/member/Member.java
src/main/java/com/mozip/domain/project/Project.java
src/main/java/com/mozip/domain/project/ProjectRepository.java
src/main/java/com/mozip/dto/resp/ProjectListDto.java
src/main/java/com/mozip/service/ProjectService.java
src/main/java/com/mozip/web/ProjectController.java
src/main/resources/mappers/ProjectMapper.xml
src/main/resources/mappers/TeamnoteMapper.xml

<Project 데이터를 들고오는 예시>
1. Project 클래스와 ProjectRepository 인터페이스를 domain/project 패키지에 생성
2. Project 클래스는 Project 테이블에 맞게 컬럼을 맞춰주고 @AllArgsConstrutor , @Getter , @Setter 선언
3. ProjectRepository 인터페이스에는 쿼리1개를 실행할 메서드를 생성(전달값, 반환값에 맞게 잘 적어야함)
4. 반환값이 있다면 반환 데이터에 맞는 DTO를 생성, dto/resp/project 패키지에 생성(응답이라면 dto/req/project 에 생성)
5. Service 에서는 데이터들고오는 로직을 실행하는 메서드를 생성후 내부에서 ProjectRepository 객체를 통해 쿼리메서드 호출, 반환 DTO를 Controller 에 전달
6. Controller 는 Service 에서 메서드를 호출한 후 반환값을 받아 콘솔에 데이터가 제대로 넘어왔는지 체크

Feat: DB에서 데이터 들고오는 예제

---

src/main/java/com/mozip/web/ProjectController.java

상세페이지 분실코드 복구 및 클래스 코드 리팩토링
resolved: #45

[#45]Fix: 프로젝트 상세페이지 수정

---

src/main/java/com/mozip/domain/project/ProjectRepository.java
src/main/java/com/mozip/web/ProjectController.java

Fix:Mapper(Repository)클래스 수정

---

src/main/java/com/mozip/domain/project/ProjectRepository.java
src/main/java/com/mozip/dto/req/ProjectLikeDto.java
src/main/java/com/mozip/service/ProjectService.java
src/main/java/com/mozip/web/ProjectController.java
src/main/java/com/mozip/web/api/ApiProjectController.java
src/main/resources/mappers/ProjectMapper.xml
src/main/resources/static/css/detail.css
src/main/resources/templates/project/show_detail.html

memberId와 projecId를 식별하여 해당 프로젝트의 좋아요를 클릭/취소 할 수 있음
resolve:#51

[#51]Feat: 좋아요 버튼 기능

---

src/main/java/com/mozip/domain/likes/Likes.java
src/main/java/com/mozip/domain/likes/LikesRepository.java
src/main/java/com/mozip/domain/project/ProjectRepository.java
src/main/java/com/mozip/service/LikesService.java
src/main/java/com/mozip/service/ProjectService.java
src/main/java/com/mozip/web/api/ApiProjectController.java
src/main/resources/mappers/LikesMapper.xml
src/main/resources/mappers/ProjectMapper.xml
src/main/resources/static/css/detail.css
src/main/resources/templates/index.html
src/main/resources/templates/project/show_detail.html

[#54]Rename: Likes파일 따로 분리하기

---

src/main/java/com/mozip/domain/project/ProjectRepository.java
src/main/java/com/mozip/dto/resp/ProjectEditDto.java
src/main/java/com/mozip/service/ProjectService.java
src/main/java/com/mozip/util/Util.java
src/main/java/com/mozip/web/ProjectController.java
src/main/java/com/mozip/web/api/ApiProjectController.java
src/main/resources/mappers/ProjectMapper.xml
src/main/resources/static/css/detail.css
src/main/resources/templates/project/recruit_create.html
src/main/resources/templates/project/recruit_detail.html
src/main/resources/templates/project/recruit_edit.html
src/main/resources/templates/project/show_detail.html

프로젝트모집 수정/삭제 기능 구현
프로젝트모집 수정/작성 시 날짜데이터 오늘 날짜 이전이면 막음

프로젝트모집 수정/삭제 기능 구현

---

src/main/resources/static/js/02donggun.js
src/main/resources/templates/member/mypage_edit.html

기술스택부분 ui변경, ajax통신 스크립트 코드 02donggun.js로 옮겨 유효성검사 하도록 수정
resolved: #59

[#59]Feat: 마이페이지 ui 수정

---

src/main/java/com/mozip/dto/req/MypageEditDto.java
src/main/java/com/mozip/dto/req/UpdateMypageEditDto.java
src/main/java/com/mozip/dto/resp/MypageDto.java
src/main/java/com/mozip/dto/resp/NewMemberListDto.java
src/main/java/com/mozip/dto/resp/ProjectDetailDto.java
src/main/java/com/mozip/dto/resp/ProjectEditDto.java
src/main/java/com/mozip/dto/resp/ProjectListDto.java
src/main/java/com/mozip/dto/resp/RecruitListDto.java
src/main/java/com/mozip/dto/resp/ShowDetailDto.java
src/main/java/com/mozip/dto/resp/ShowEditDto.java
src/main/java/com/mozip/dto/resp/TeamnoteListDto.java
src/main/java/com/mozip/service/MemberService.java
src/main/java/com/mozip/service/ProjectService.java
src/main/java/com/mozip/service/TeamService.java
src/main/java/com/mozip/web/api/ApiMemberController.java
src/main/java/com/mozip/web/api/ApiProjectController.java
src/main/resources/mappers/ProjectMapper.xml

Oracle -> MySQL 변경으로 쿼리 및 데이터 타입 변경, ProjectService.java에 deleteProject()에 readOnly=false 추가
resolved: #98

[#98]Feat: MySql 쿼리 변경 및 NCLOB 타입 삭제

---

README.md
build.gradle
src/main/java/com/mozip/config/SecurityConfig.java
src/main/java/com/mozip/config/auth/PrincipalDetails.java
src/main/java/com/mozip/config/auth/PrincipalDetailsService.java
src/main/java/com/mozip/domain/member/AuthRepository.java
src/main/java/com/mozip/domain/member/Member.java
src/main/java/com/mozip/domain/member/Role.java
src/main/java/com/mozip/dto/resp/ProjectEditDto.java
src/main/java/com/mozip/service/AuthService.java
src/main/java/com/mozip/web/AuthController.java
src/main/java/com/mozip/web/MemberController.java
src/main/java/com/mozip/web/ProjectController.java
src/main/java/com/mozip/web/api/ApiEmailController.java
src/main/java/com/mozip/web/api/ApiMemberController.java
src/main/java/com/mozip/web/api/ApiProjectController.java
src/main/resources/mappers/AuthMapper.xml
src/main/resources/templates/auth/login.html
src/main/resources/templates/fragment/header.html
src/main/resources/templates/member/mypage.html
src/main/resources/templates/project/recruit_create.html
src/main/resources/templates/project/recruit_detail.html
src/main/resources/templates/project/recruit_list.html
src/main/resources/templates/project/show_detail.html

1. 스프링 시큐리티 및 OAuth2 의존성 추가
2. 기존 세션 저장 방식 변경
3. 타임리프 세션 코드 전부 수정
resolved: #102
이후 프로젝트자랑 수정하면서 변경해줘야함

[#102]스프링 시큐리티 추가

---

src/main/java/com/mozip/web/ProjectController.java
src/main/java/com/mozip/web/TeamController.java
src/main/resources/application-dev.yml
src/main/resources/templates/project/recruit_list.html
src/test/java/com/mozip/MozipApplicationTests.java

Fix: 타임리프 경로 수정

---

src/main/java/com/mozip/dto/req/member/JoinMemberDto.java

JoinMemberDto에 @NoArgsConstructor @AllArgsConstructor 추가
resolved: #106

[#106] Feat: 어노테이션 추가

---

src/main/java/com/mozip/config/SecurityConfig.java
src/main/java/com/mozip/domain/member/AuthRepository.java
src/main/java/com/mozip/dto/req/member/FindPwDto.java
src/main/java/com/mozip/service/AuthService.java
src/main/java/com/mozip/web/AuthController.java
src/main/resources/mappers/AuthMapper.xml
src/main/resources/templates/auth/find_id.html
src/main/resources/templates/auth/update_password.html

비밀번호 찾기 : 폼 제출, 이름,이메일,전화번호 입력받아 맴버가 있으면 재설정 페이지로
비밀번호 재설정: 찾기 페이지에서 이메일값을 받아와서 API 통신 안됨, controller에서 리턴으로 script alert
resolved: #76

[#76] Feat: 비밀번호 찾기 및 재설정 구현

---

src/main/resources/templates/member/mypage_edit.html
src/main/resources/templates/project/recruit_create.html
src/main/resources/templates/project/recruit_edit.html
src/main/resources/templates/project/show_edit.html
src/main/resources/templates/project/show_list.html

셀렉트 창 옵션 추가

---

src/main/java/com/mozip/config/SecurityConfig.java
src/main/java/com/mozip/config/auth/PrincipalDetails.java
src/main/java/com/mozip/config/auth/PrincipalOauth2UserService.java
src/main/java/com/mozip/domain/member/MemberRepository.java
src/main/java/com/mozip/service/AuthService.java
src/main/java/com/mozip/service/MemberService.java
src/main/java/com/mozip/web/AuthController.java
src/main/java/com/mozip/web/MemberController.java
src/main/java/com/mozip/web/api/ApiMemberController.java
src/main/resources/mappers/MemberMapper.xml
src/main/resources/templates/fragment/header.html
src/main/resources/templates/project/recruit_detail.html

회원탈퇴 기능 구현

---

src/main/java/com/mozip/dto/req/member/FindPwDto.java
src/main/java/com/mozip/dto/req/member/JoinMemberDto.java
src/main/java/com/mozip/dto/req/member/LoginDto.java
src/main/java/com/mozip/dto/req/member/UpdateMypageEditDto.java
src/main/java/com/mozip/dto/req/project/FindEmailDto.java
src/main/java/com/mozip/dto/req/project/ProjectCreateDto.java
src/main/java/com/mozip/service/ProjectService.java
src/main/resources/templates/project/recruit_edit.html

프로젝트모집 카테고리 필터 버그해결

---

src/main/java/com/mozip/domain/project/ProjectRepository.java
src/main/java/com/mozip/service/ProjectService.java
src/main/java/com/mozip/web/ProjectController.java
src/main/java/com/mozip/web/api/ApiProjectController.java
src/main/resources/mappers/ProjectMapper.xml
src/main/resources/templates/project/recruit_list.html

프로젝트 목록페이지만 무한스크롤 구현
필터, 검색 미적용

Feat: 무한스크롤 구현

---

src/main/java/com/mozip/domain/project/ProjectRepository.java
src/main/java/com/mozip/service/ProjectService.java
src/main/resources/mappers/ProjectMapper.xml

Feat: 프로젝트 기본 샘플이미지 세팅

---

build.gradle
src/main/java/com/mozip/config/MyBatisConfig.java
src/main/resources/application-dev.yml
src/main/resources/logback-spring.xml

1. build.gradle 의존성 추가
2. application.yml 추가설정
3. Logback 파일 추가
4. MyBatis 설정 클래스 수정
resolved: #120

[#120]Feat: Mybatis 로그 설정

---

src/main/java/com/mozip/domain/project/ProjectRepository.java
src/main/java/com/mozip/service/ProjectService.java
src/main/resources/mappers/ProjectMapper.xml

프로젝트 모집역할, 모집스킬, 북마크, 프로젝트 맴버, 신청목록, 좋아요 쿼리 추가 및 DB 삭제
resolved: #127

프로젝트 삭제 쿼리 및 로직 수정

---

build.gradle
src/main/java/com/mozip/config/SecurityConfig.java
src/main/java/com/mozip/config/WebConfig.java
src/main/java/com/mozip/web/ProjectController.java
src/main/java/com/mozip/web/api/ApiProjectController.java
src/main/resources/application-dev.yml
src/main/resources/templates/fragment/header.html
src/main/resources/templates/project/recruit_edit.html
src/main/resources/templates/project/recruit_job.html

사람인API 연동 세팅

---

src/main/resources/templates/auth/find_id.html
src/main/resources/templates/auth/find_password.html
src/main/resources/templates/auth/update_password.html

find_id, find_password, update_password 액션 타임리프 수정

---

src/main/java/com/mozip/config/ApplicationConfig.java
src/main/java/com/mozip/config/SecurityConfig.java
src/main/java/com/mozip/config/WebConfig.java
src/main/java/com/mozip/web/api/ApiSaraminController.java
src/main/resources/templates/project/recruit_job.html

1. 채용공고 API 연동하여 데이터 가져오기
2. 검색조건 및 필터에 따른 데이터 가져오기
3. 무한스크롤 적용
resolved: #137

[#137]Feat: 사람인 채용공고 API 연동

---

src/main/java/com/mozip/dto/req/project/ProjectCreateDto.java
src/main/resources/static/css/create.css
src/main/resources/static/js/dynamicSkills.js
src/main/resources/static/js/recruit_create.js
src/main/resources/static/js/recruit_edit.js
src/main/resources/templates/project/recruit_create.html
src/main/resources/templates/project/recruit_edit.html

1. recruit_create.js, recruite_edit.js에 글자수 제한 코드 추가
2. dynamicSkills.js에 기술스택 갯수 6로 제한하는 코드 추가
3. recruit_create.html, recruite_edit.html, create.css 수정
resolved: #146

[#146]Fix: 프로젝트 작성,수정글 제목,주제,소개 글자수 제한 및 기술스택 갯수 제한

---

src/main/resources/static/js/show_list.js
src/main/resources/templates/project/show_detail.html

1. 프로젝트 자랑 리스트 : 기술스택 해당되지 않는 기술 선택시 안내문구 영역수정
2. 프로젝트 자랑 상세 : 작성자 프로필 css 수정
resolved: #148

[#148]Design: 프로젝트 자랑 css

---

src/main/java/com/mozip/config/MyBatisConfig.java
src/main/java/com/mozip/domain/member/Member.java
src/main/java/com/mozip/domain/member/Role.java
src/main/java/com/mozip/handler/RoleTypeHandler.java
src/main/resources/mappers/AuthMapper.xml
src/main/resources/static/js/recruit_detail.js
src/main/resources/templates/project/recruit_detail.html

1. 로그인 시 Member 테이블 조회 쿼리 수정(매핑이 잘못돼서 프로젝트 참여신청 시 필요한 데이터를 못갖고왔음)
2. AuthMapper.xml 에 resultmap 생성
3. Java Enum 과 매핑하기 위해 RoleTypeHandler 클래스 생성
4. MyBatisConfig 클래스 수정
resolved: #150

[#150]Fix: 프로젝트 참여신청 로직 변경

---

src/main/resources/mappers/ProjectMapper.xml
src/main/resources/templates/project/recruit_list.html

1. 검색쿼리 수정 
2. 카테고리, 셀렉트, 타입 필터 쿼리 수정 
3. 무한스크롤 쿼리 수정

프로젝트 모집 리스트 쿼리 수정 

---

src/main/resources/static/js/recruit_detail.js
src/main/resources/static/js/show_detail.js
src/main/resources/templates/project/recruit_detail.html
src/main/resources/templates/project/show_detail.html

1. recruit_detail, show_detail js파일에 클립보드 api 코드 추가
2. recruit_detail.html, show_detail.html 공유하기 a태그에 onClick 함수 추가
resolved: #161

[#161] Feat: 공유하기 버튼 클릭시 현재 url 복사

---

src/main/resources/static/js/recruit_detail.js
src/main/resources/static/js/show_detail.js

recruit_detail.js, show_detail.js에 copyToClipboard() 함수 수정
resolved: #165

[#165] Fix: 공유하기 버그 수정

---

src/main/resources/static/js/mypage.js
src/main/resources/templates/member/mypage.html

1. mypage.html keep 클래스에 함수 추가
2. mypage.js 생성 및 필터링 함수 생성
resolved: #163

[#163] Feat: 마이페이지 북마크 필터링

---

src/main/java/com/mozip/domain/project/ProjectRepository.java
src/main/java/com/mozip/service/MemberService.java
src/main/resources/mappers/ProjectMapper.xml

Fix: 회원탈퇴 로직 추가

---

src/main/resources/static/css/mypage.css
src/main/resources/static/js/mypage.js
src/main/resources/templates/member/mypage.html

mypage.js에 notProjectMessage() 함수에 innerHTML으로 메시지 추가

Fix: 마이페이지 북마크 스타일 수정

---

src/main/java/com/mozip/domain/project/ProjectRepository.java
src/main/java/com/mozip/dto/req/project/ShowUpdateDto.java
src/main/java/com/mozip/service/ProjectService.java
src/main/java/com/mozip/web/api/ApiProjectController.java
src/main/resources/mappers/ProjectMapper.xml
src/main/resources/templates/member/myproject_list.html
src/main/resources/templates/project/show_detail.html

1. 멤버가 작성한 프로젝트목록 페이지 생성 후 연결
2. 프로젝트 자랑 변환 후 자랑 상세페이지 이동

Feat: 프로젝트모집->자랑 변환
